-- settings.lua
-- The recipe restore is unconditional (the mod's whole purpose), so it has
-- no toggles. Only the unrelated crashed-ship tweak keeps a switch.

data:extend({
  {
    type = "bool-setting",
    name = "etech-pickup-crashed-ship",
    setting_type = "startup",
    default_value = true,
    order = "a",
    localised_name = {"", "Allow picking up and re-placing the crashed ship"},
    localised_description = {"", "Makes crash-site spaceship parts minable and gives placement items so you can pick them up and put them back down. Unrelated to the AAI recipe restore, hence its own switch."},
  },
  {
    type = "bool-setting",
    name = "etech-beacon-all-modules",
    setting_type = "startup",
    default_value = true,
    order = "b",
    localised_name = {"", "Allow all modules in beacons"},
    localised_description = {"", "Lets every beacon accept every module type, including productivity and quality modules. Applies to modded beacons too."},
  },
  {
    type = "bool-setting",
    name = "etech-quality-asteroid",
    setting_type = "startup",
    default_value = true,
    order = "c",
    localised_name = {"", "Allow quality modules in asteroid crushing/reprocessing"},
    localised_description = {"", "Enables quality on all asteroid crushing and reprocessing recipes so quality modules in the crusher take effect."},
  },
  {
    type = "int-setting",
    name = "etech-nuclear-fuel-stack",
    setting_type = "startup",
    default_value = 1,
    minimum_value = 1,
    maximum_value = 1000,
    order = "d",
    localised_name = {"", "Nuclear fuel stack size"},
    localised_description = {"", "Stack size for nuclear fuel. Vanilla is 1."},
  },
  {
    type = "int-setting",
    name = "etech-artillery-shell-stack",
    setting_type = "startup",
    default_value = 1,
    minimum_value = 1,
    maximum_value = 1000,
    order = "e",
    localised_name = {"", "Artillery shell stack size"},
    localised_description = {"", "Stack size for artillery shells. Vanilla is 1."},
  },
  {
    type = "bool-setting",
    name = "etech-ag-science-spoils",
    setting_type = "startup",
    default_value = true,
    order = "f",
    localised_name = {"", "Agricultural science pack spoils"},
    localised_description = {"", "When on (default, vanilla), agricultural science packs spoil normally. Turn off to stop them spoiling."},
  },
  {
    type = "bool-setting",
    name = "etech-restore-nuclear-fuel",
    setting_type = "startup",
    default_value = false,
    order = "g",
    localised_name = {"", "Restore nuclear fuel crafting (Krastorio 2)"},
    localised_description = {"", "Krastorio 2 hides vanilla nuclear fuel (the rocket-fuel + U-235 train fuel). Turn on to bring the item and recipe back, unlocked by Kovarex enrichment like vanilla. Off by default because hiding it is a deliberate K2 balance choice."},
  },
  {
    type = "bool-setting",
    name = "etech-teleport-shortcut",
    setting_type = "startup",
    default_value = false,
    order = "h",
    localised_name = {"", "Teleport-to-player shortcut (experimental)"},
    localised_description = {"", "Adds a toolbar shortcut that teleports you to another player. One other player online: click teleports straight to them. Several: a picker window opens. Experimental multiplayer fun, off by default."},
  },
  {
    type = "bool-setting",
    name = "etech-teleporters",
    setting_type = "startup",
    default_value = false,
    order = "j",
    localised_name = {"", "Teleporter pads"},
    localised_description = {"", "Adds buildable teleporter pads (researched with chemical science). Walk onto a pad to open a map of your other pads and click one to teleport there. Pads are named, renamable, and shown as map tags. Port of the Teleporters mod by Klonan, updated for Factorio 2.1; off by default."},
  },
  {
    type = "double-setting",
    name = "etech-teleporter-energy-mj",
    setting_type = "runtime-global",
    default_value = 10,
    minimum_value = 0,
    maximum_value = 200,
    order = "ta",
    localised_name = {"", "Teleporter: energy per teleport (MJ)"},
    localised_description = {"", "Energy drained from the DESTINATION pad's buffer per teleport. An unpowered pad can't be teleported to. 0 = teleporting is free (the original Teleporters mod behavior). Pad buffer is 200 MJ."},
  },
  {
    type = "double-setting",
    name = "etech-teleporter-energy-distance-mj",
    setting_type = "runtime-global",
    default_value = 0,
    minimum_value = 0,
    maximum_value = 100,
    order = "tb",
    localised_name = {"", "Teleporter: extra energy per 100 tiles (MJ)"},
    localised_description = {"", "Additional energy cost per 100 tiles of distance between the pads (same surface only). 0 = distance doesn't matter."},
  },
  {
    type = "bool-setting",
    name = "etech-teleporter-cross-surface",
    setting_type = "runtime-global",
    default_value = true,
    order = "tc",
    localised_name = {"", "Teleporter: allow cross-surface teleporting"},
    localised_description = {"", "When on, pads on other surfaces (planets, space platforms) appear in the teleporter list. Turn off to restrict teleporting to the surface you're on."},
  },
  {
    type = "double-setting",
    name = "etech-teleporter-cross-surface-multiplier",
    setting_type = "runtime-global",
    default_value = 1,
    minimum_value = 0,
    maximum_value = 100,
    order = "td",
    localised_name = {"", "Teleporter: cross-surface energy multiplier"},
    localised_description = {"", "The per-teleport energy cost is multiplied by this when teleporting between surfaces. 1 = same as a local jump."},
  },
  {
    type = "bool-setting",
    name = "etech-teleporter-hide-platforms",
    setting_type = "runtime-global",
    default_value = false,
    order = "te",
    localised_name = {"", "Teleporter: hide space platforms from the list"},
    localised_description = {"", "When on, pads on space platforms don't appear under \"All surfaces\" (reduces noise with many ships). Selecting a platform in the surface dropdown still shows its pads."},
  },
  {
    type = "bool-setting",
    name = "etech-teleporter-remote",
    setting_type = "runtime-global",
    default_value = true,
    order = "tf",
    localised_name = {"", "Teleporter: wireless remote shortcut"},
    localised_description = {"", "Toolbar shortcut that opens the teleporter list from anywhere (after the Teleporter technology is researched). Energy is drained from the destination pad, so it can't take you to an unpowered base."},
  },
  {
    type = "double-setting",
    name = "etech-teleporter-remote-multiplier",
    setting_type = "runtime-global",
    default_value = 2,
    minimum_value = 0,
    maximum_value = 100,
    order = "tg",
    localised_name = {"", "Teleporter: remote energy multiplier"},
    localised_description = {"", "The per-teleport energy cost is multiplied by this when using the wireless remote (no pad under your feet). Convenience premium; 1 = same as a pad-to-pad jump."},
  },
  {
    type = "bool-setting",
    name = "etech-teleporter-return-enabled",
    setting_type = "runtime-global",
    default_value = true,
    order = "th",
    localised_name = {"", "Teleporter: return teleport"},
    localised_description = {"", "After a remote teleport, the teleporter list offers a free Return entry (with a live camera view) that takes you back to where you were standing. One slot, overwritten by the next remote jump."},
  },
  {
    type = "double-setting",
    name = "etech-teleporter-return-grace-min",
    setting_type = "runtime-global",
    default_value = 10,
    minimum_value = 0,
    maximum_value = 1440,
    order = "ti",
    localised_name = {"", "Teleporter: return time limit (minutes)"},
    localised_description = {"", "How long the Return entry stays available after a remote teleport. 0 = no time limit."},
  },
  {
    type = "bool-setting",
    name = "etech-teleporter-alerts",
    setting_type = "runtime-global",
    default_value = true,
    order = "tk-1",
    localised_name = {"", "Teleporter: unpowered pad alerts"},
    localised_description = {"", "Raises a map alert while a teleporter pad's energy buffer sits empty (only when teleporting costs energy). An unpowered pad can't be teleported to."},
  },
  {
    type = "int-setting",
    name = "etech-teleporter-preview-size",
    setting_type = "runtime-global",
    default_value = 200,
    minimum_value = 96,
    maximum_value = 512,
    order = "tk-1b",
    localised_name = {"", "Teleporter: pad preview size (px)"},
    localised_description = {"", "Size of the minimap preview per pad in the destination list. Smaller = more pads on screen. Was 256 before 0.10.1; default is now 200."},
  },
  {
    type = "double-setting",
    name = "etech-teleporter-sound-volume",
    setting_type = "runtime-global",
    default_value = 1,
    minimum_value = 0,
    maximum_value = 2,
    order = "tk-2",
    localised_name = {"", "Teleporter: sound volume"},
    localised_description = {"", "Volume of the teleport sound the teleporting player hears. 0 = silent, 1 = default, 2 = double."},
  },
  {
    type = "bool-setting",
    name = "etech-teleporter-players-section",
    setting_type = "runtime-global",
    default_value = true,
    order = "tj",
    localised_name = {"", "Teleporter: players in the teleporter list"},
    localised_description = {"", "Shows your team's online players at the top of the teleporter list with map previews — click one to teleport to them (free, like the teleport-to-player shortcut)."},
  },
  {
    type = "bool-setting",
    name = "etech-resource-markers",
    setting_type = "startup",
    default_value = false,
    order = "k",
    localised_name = {"", "Resource map markers"},
    localised_description = {"", "Automatically tags resource patches on the map: one marker per patch with the resource icon and total amount (oil and other infinite resources show well count and average yield). Markers update as the map gets charted and ore gets mined. Delete a marker to hide that patch's marker for good; /etech-markers-rebuild rescans everything. Written for E-Tech (public domain), inspired by the abandoned Resource Map Label Marker mod."},
  },
  {
    type = "int-setting",
    name = "etech-markers-min-size",
    setting_type = "runtime-global",
    default_value = 1,
    minimum_value = 1,
    maximum_value = 10000,
    order = "tk",
    localised_name = {"", "Resource markers: minimum patch size"},
    localised_description = {"", "Patches with fewer resource tiles than this don't get a map marker. 1 = mark everything."},
  },
  {
    type = "bool-setting",
    name = "etech-jetpack-ui",
    setting_type = "startup",
    default_value = false,
    order = "n",
    localised_name = {"", "Jetpack fuel HUD"},
    localised_description = {"", "Needs the Jetpack mod. While flying, shows a small movable window with the current fuel, inventory count, burn bar, and estimated remaining flight time. Port of Puppy's Jetpack UI with the window-position reset bug fixed; automatically skipped if the original mod is installed. Off by default."},
  },
  {
    type = "bool-setting",
    name = "etech-total-productivity",
    setting_type = "startup",
    default_value = false,
    order = "m",
    localised_name = {"", "Total productivity (prod modules for everything)"},
    localised_description = {"", "Allows productivity modules on recipes the game normally forbids: belts, inserters, rails, pipes, solar panels, walls, ammo, equipment, and more. Four group toggles below pick the categories. Port of the abandoned Total Productivity mod by AivanF; automatically skipped if the original mod is installed. Off by default."},
  },
  {
    type = "bool-setting",
    name = "etech-prod-logistics",
    setting_type = "startup",
    default_value = true,
    order = "m-1",
    localised_name = {"", "Total productivity: logistics"},
    localised_description = {"", "Belts, inserters, containers, robots, rails, trains, vehicles, pipes, poles, combinators, and floor tiles."},
  },
  {
    type = "bool-setting",
    name = "etech-prod-buildings",
    setting_type = "startup",
    default_value = true,
    order = "m-2",
    localised_name = {"", "Total productivity: buildings"},
    localised_description = {"", "Miners, assemblers, furnaces, labs, roboports, power (solar, accumulators, reactors, generators), radar, walls and gates, and Space Age platform parts."},
  },
  {
    type = "bool-setting",
    name = "etech-prod-military",
    setting_type = "startup",
    default_value = true,
    order = "m-3",
    localised_name = {"", "Total productivity: military"},
    localised_description = {"", "Turrets, guns, ammo, capsules, land mines, armor, and equipment."},
  },
  {
    type = "bool-setting",
    name = "etech-prod-misc",
    setting_type = "startup",
    default_value = true,
    order = "m-4",
    localised_name = {"", "Total productivity: modules & misc"},
    localised_description = {"", "Modules, beacons, repair packs, and launchable satellites/probes."},
  },
  {
    type = "bool-setting",
    name = "etech-map-settings",
    setting_type = "startup",
    default_value = false,
    order = "o",
    localised_name = {"", "Edit map settings in-game"},
    localised_description = {"", "Toolbar shortcut that opens an editor for map settings (pollution, evolution, enemy expansion, peaceful/no-enemies mode, spoilage rate) and per-surface map generation settings (admins only to apply). Port of the abandoned Edit Map Settings mod; automatically skipped if the original mod is installed. Off by default."},
  },
  {
    type = "bool-setting",
    name = "etech-void",
    setting_type = "startup",
    default_value = false,
    order = "p",
    localised_name = {"", "Void chest & void pipe"},
    localised_description = {"", "Adds a cheap void chest (destroys any item put in it) and void pipe (destroys any fluid pumped in), unlocked by a small early technology. Port of the abandoned Easy Void mod; automatically skipped if the original mod is installed. Existing placed voids from the original survive the switch. Off by default."},
  },
  {
    type = "double-setting",
    name = "etech-void-tint-r",
    setting_type = "startup",
    minimum_value = 0,
    maximum_value = 1,
    default_value = 0.75,
    order = "p-1",
    localised_name = {"", "Void: red tint factor"},
    localised_description = {"", "Red part of the void chest/pipe color tint (0.0 - 1.0)."},
  },
  {
    type = "double-setting",
    name = "etech-void-tint-g",
    setting_type = "startup",
    minimum_value = 0,
    maximum_value = 1,
    default_value = 0,
    order = "p-2",
    localised_name = {"", "Void: green tint factor"},
    localised_description = {"", "Green part of the void chest/pipe color tint (0.0 - 1.0)."},
  },
  {
    type = "double-setting",
    name = "etech-void-tint-b",
    setting_type = "startup",
    minimum_value = 0,
    maximum_value = 1,
    default_value = 1,
    order = "p-3",
    localised_name = {"", "Void: blue tint factor"},
    localised_description = {"", "Blue part of the void chest/pipe color tint (0.0 - 1.0)."},
  },
  {
    type = "bool-setting",
    name = "etech-void-filtered",
    setting_type = "startup",
    default_value = false,
    order = "p-3b",
    localised_name = {"", "Void: filtered void chest"},
    localised_description = {"", "Adds a second, greenish void chest that only destroys the items YOU pick: open it and set an infinity filter to \"exactly 0\" for each item to void — everything else just sits. Same tech unlock as the normal void chest. Needs the void toggle above. Off by default."},
  },
  {
    type = "int-setting",
    name = "etech-void-slots",
    setting_type = "startup",
    minimum_value = 1,
    maximum_value = 10,
    default_value = 4,
    order = "p-4",
    localised_name = {"", "Void: chest slots"},
    localised_description = {"", "Number of inventory slots in the void chest (1 - 10)."},
  },
  {
    type = "bool-setting",
    name = "etech-fps-thrusters",
    setting_type = "startup",
    default_value = false,
    order = "q",
    localised_name = {"", "FPS-friendly thrusters (no plumes)"},
    localised_description = {"", "Removes the animated exhaust plumes from space platform thrusters — the biggest FPS drain on large platforms. Port of the abandoned FPS Friendly Thrusters mod; automatically skipped if the original mod is installed. Off by default."},
  },
  {
    type = "bool-setting",
    name = "etech-fusion-passthrough",
    setting_type = "startup",
    default_value = false,
    order = "r",
    localised_name = {"", "Pass-through fusion generators"},
    localised_description = {"", "Gives the fusion generator input-output plasma connections on all four sides so generators can be chained without separate plasma lines. Port of the abandoned Pass-through fusion generator mod; automatically skipped if the original mod is installed. Off by default."},
  },
  {
    type = "bool-setting",
    name = "etech-colorful-biochamber",
    setting_type = "startup",
    default_value = false,
    order = "s",
    localised_name = {"", "Colorful biochamber"},
    localised_description = {"", "Recolors the biochamber's pools, dome and windows per recipe (RGB working visualisations), so you can tell what a biochamber is making at a glance. Port of the abandoned Colorful Biochamber mod (public domain); automatically skipped if the original mod is installed. Needs Space Age; off by default."},
  },
  {
    type = "bool-setting",
    name = "etech-copy-paste-modules",
    setting_type = "startup",
    default_value = false,
    order = "u",
    localised_name = {"", "Copy modules with machine settings"},
    localised_description = {"", "Shift-click paste copies modules too: taken straight from your inventory (old modules handed back), with a bot request for anything missing. Handles ghosts and remote view; furnaces, labs and beacons become cross-pastable. Port of the abandoned Copy Paste Modules mod by kajacx; automatically skipped if the original mod is installed. Off by default."},
  },
  {
    type = "bool-setting",
    name = "etech-cpm-enabled",
    setting_type = "runtime-per-user",
    default_value = true,
    order = "u-1",
    localised_name = {"", "Copy modules: active for me"},
    localised_description = {"", "Per-player switch for the copy-modules-on-paste behavior. Only matters when the startup toggle is on."},
  },
  {
    type = "bool-setting",
    name = "etech-factory-hub",
    setting_type = "startup",
    default_value = false,
    order = "v",
    localised_name = {"", "Factory outlet, inlet & sensor (Factorissimo)"},
    localised_description = {"", "Adds the factory outlet (pulls items out of provider chests INSIDE Factorissimo factory buildings for the local logistic network), the factory inlet (distributes its contents into requester chests inside the factories) and the factory sensor (interior stock as circuit signals). Bots can't fly into factories, so these teleport the items across. One outlet per surface; each planet's outlet only sees the factories on that planet. Unlocked alongside logistic robotics and Factorissimo's chest connections. Needs Factorissimo 3; off by default."},
  },
  -- The former factory-hub tuning settings (slots, stacks per item, active
  -- providers only, energy per item, range, nested reach) are fixed values
  -- since 0.17.0 - see factory-hub/data.lua and factory-hub/control.lua.
  {
    type = "bool-setting",
    name = "etech-quality-module-slots",
    setting_type = "startup",
    default_value = true,
    order = "w",
    localised_name = {"", "Quality adds module slots to all machines"},
    localised_description = {"", "Every machine that has at least one module slot gains extra slots at higher quality - assemblers, furnaces, rocket silos, beacons, mining drills, and labs (modded ones included). Machines with no module slots are untouched. Replaces the retired QualityEffectsFixed mod with a blanket rule. Needs the Quality mod; on by default."},
  },
  {
    type = "bool-setting",
    name = "etech-gleba-uranium",
    setting_type = "startup",
    default_value = false,
    order = "i",
    localised_name = {"", "Uranium bacteria on Gleba (Space Age)"},
    localised_description = {"", "Adds uranium bacteria, mirroring iron/copper bacteria: jelly gives a 1% chance of uranium bacteria (Jellynut tech), bacteria + bioflux multiplies it in a biochamber (Bacteria cultivation tech), and it spoils into uranium ore. Port of the abandoned Simple Gleba Uranium mod by cindersash. Needs Space Age; off by default."},
  },
})
