-- settings.lua
-- The recipe restore is unconditional (the mod's whole purpose), so it has
-- no toggles. Only the unrelated crashed-ship tweak keeps a switch.

data:extend({
  {
    type = "bool-setting",
    name = "etech-pickup-crashed-ship",
    setting_type = "startup",
    default_value = true,
    order = "a",
    localised_name = {"", "Allow picking up and re-placing the crashed ship"},
    localised_description = {"", "Makes crash-site spaceship parts minable and gives placement items so you can pick them up and put them back down. Unrelated to the AAI recipe restore, hence its own switch."},
  },
  {
    type = "bool-setting",
    name = "etech-beacon-all-modules",
    setting_type = "startup",
    default_value = true,
    order = "b",
    localised_name = {"", "Allow all modules in beacons"},
    localised_description = {"", "Lets every beacon accept every module type, including productivity and quality modules. Applies to modded beacons too."},
  },
  {
    type = "bool-setting",
    name = "etech-quality-asteroid",
    setting_type = "startup",
    default_value = true,
    order = "c",
    localised_name = {"", "Allow quality modules in asteroid crushing/reprocessing"},
    localised_description = {"", "Enables quality on all asteroid crushing and reprocessing recipes so quality modules in the crusher take effect."},
  },
  {
    type = "int-setting",
    name = "etech-nuclear-fuel-stack",
    setting_type = "startup",
    default_value = 1,
    minimum_value = 1,
    maximum_value = 1000,
    order = "d",
    localised_name = {"", "Nuclear fuel stack size"},
    localised_description = {"", "Stack size for nuclear fuel. Vanilla is 1."},
  },
  {
    type = "int-setting",
    name = "etech-artillery-shell-stack",
    setting_type = "startup",
    default_value = 1,
    minimum_value = 1,
    maximum_value = 1000,
    order = "e",
    localised_name = {"", "Artillery shell stack size"},
    localised_description = {"", "Stack size for artillery shells. Vanilla is 1."},
  },
  {
    type = "bool-setting",
    name = "etech-ag-science-spoils",
    setting_type = "startup",
    default_value = true,
    order = "f",
    localised_name = {"", "Agricultural science pack spoils"},
    localised_description = {"", "When on (default, vanilla), agricultural science packs spoil normally. Turn off to stop them spoiling."},
  },
  {
    type = "bool-setting",
    name = "etech-restore-nuclear-fuel",
    setting_type = "startup",
    default_value = false,
    order = "g",
    localised_name = {"", "Restore nuclear fuel crafting (Krastorio 2)"},
    localised_description = {"", "Krastorio 2 hides vanilla nuclear fuel (the rocket-fuel + U-235 train fuel). Turn on to bring the item and recipe back, unlocked by Kovarex enrichment like vanilla. Off by default because hiding it is a deliberate K2 balance choice."},
  },
  {
    type = "bool-setting",
    name = "etech-teleport-shortcut",
    setting_type = "startup",
    default_value = false,
    order = "h",
    localised_name = {"", "Teleport-to-player shortcut (experimental)"},
    localised_description = {"", "Adds a toolbar shortcut that teleports you to another player. One other player online: click teleports straight to them. Several: a picker window opens. Experimental multiplayer fun, off by default."},
  },
  {
    type = "bool-setting",
    name = "etech-teleporters",
    setting_type = "startup",
    default_value = false,
    order = "j",
    localised_name = {"", "Teleporter pads"},
    localised_description = {"", "Adds buildable teleporter pads (researched with chemical science). Walk onto a pad to open a map of your other pads and click one to teleport there. Pads are named, renamable, and shown as map tags. Port of the Teleporters mod by Klonan, updated for Factorio 2.1; off by default."},
  },
  {
    type = "double-setting",
    name = "etech-teleporter-energy-mj",
    setting_type = "runtime-global",
    default_value = 10,
    minimum_value = 0,
    maximum_value = 200,
    order = "ta",
    localised_name = {"", "Teleporter: energy per teleport (MJ)"},
    localised_description = {"", "Energy drained from the DESTINATION pad's buffer per teleport. An unpowered pad can't be teleported to. 0 = teleporting is free (the original Teleporters mod behavior). Pad buffer is 200 MJ."},
  },
  {
    type = "double-setting",
    name = "etech-teleporter-energy-distance-mj",
    setting_type = "runtime-global",
    default_value = 0,
    minimum_value = 0,
    maximum_value = 100,
    order = "tb",
    localised_name = {"", "Teleporter: extra energy per 100 tiles (MJ)"},
    localised_description = {"", "Additional energy cost per 100 tiles of distance between the pads (same surface only). 0 = distance doesn't matter."},
  },
  {
    type = "bool-setting",
    name = "etech-teleporter-cross-surface",
    setting_type = "runtime-global",
    default_value = true,
    order = "tc",
    localised_name = {"", "Teleporter: allow cross-surface teleporting"},
    localised_description = {"", "When on, pads on other surfaces (planets, space platforms) appear in the teleporter list. Turn off to restrict teleporting to the surface you're on."},
  },
  {
    type = "double-setting",
    name = "etech-teleporter-cross-surface-multiplier",
    setting_type = "runtime-global",
    default_value = 1,
    minimum_value = 0,
    maximum_value = 100,
    order = "td",
    localised_name = {"", "Teleporter: cross-surface energy multiplier"},
    localised_description = {"", "The per-teleport energy cost is multiplied by this when teleporting between surfaces. 1 = same as a local jump."},
  },
  {
    type = "bool-setting",
    name = "etech-teleporter-hide-platforms",
    setting_type = "runtime-global",
    default_value = false,
    order = "te",
    localised_name = {"", "Teleporter: hide space platforms from the list"},
    localised_description = {"", "When on, pads on space platforms don't appear under \"All surfaces\" (reduces noise with many ships). Selecting a platform in the surface dropdown still shows its pads."},
  },
  {
    type = "bool-setting",
    name = "etech-teleporter-remote",
    setting_type = "runtime-global",
    default_value = true,
    order = "tf",
    localised_name = {"", "Teleporter: wireless remote shortcut"},
    localised_description = {"", "Toolbar shortcut that opens the teleporter list from anywhere (after the Teleporter technology is researched). Energy is drained from the destination pad, so it can't take you to an unpowered base."},
  },
  {
    type = "double-setting",
    name = "etech-teleporter-remote-multiplier",
    setting_type = "runtime-global",
    default_value = 2,
    minimum_value = 0,
    maximum_value = 100,
    order = "tg",
    localised_name = {"", "Teleporter: remote energy multiplier"},
    localised_description = {"", "The per-teleport energy cost is multiplied by this when using the wireless remote (no pad under your feet). Convenience premium; 1 = same as a pad-to-pad jump."},
  },
  {
    type = "bool-setting",
    name = "etech-teleporter-return-enabled",
    setting_type = "runtime-global",
    default_value = true,
    order = "th",
    localised_name = {"", "Teleporter: return teleport"},
    localised_description = {"", "After a remote teleport, the teleporter list offers a free Return entry (with a live camera view) that takes you back to where you were standing. One slot, overwritten by the next remote jump."},
  },
  {
    type = "double-setting",
    name = "etech-teleporter-return-grace-min",
    setting_type = "runtime-global",
    default_value = 10,
    minimum_value = 0,
    maximum_value = 1440,
    order = "ti",
    localised_name = {"", "Teleporter: return time limit (minutes)"},
    localised_description = {"", "How long the Return entry stays available after a remote teleport. 0 = no time limit."},
  },
  {
    type = "bool-setting",
    name = "etech-teleporter-players-section",
    setting_type = "runtime-global",
    default_value = true,
    order = "tj",
    localised_name = {"", "Teleporter: players in the teleporter list"},
    localised_description = {"", "Shows your team's online players at the top of the teleporter list with map previews — click one to teleport to them (free, like the teleport-to-player shortcut)."},
  },
  {
    type = "bool-setting",
    name = "etech-resource-markers",
    setting_type = "startup",
    default_value = false,
    order = "k",
    localised_name = {"", "Resource map markers"},
    localised_description = {"", "Automatically tags resource patches on the map: one marker per patch with the resource icon and total amount (oil and other infinite resources show well count and average yield). Markers update as the map gets charted and ore gets mined. Delete a marker to hide that patch's marker for good; /etech-markers-rebuild rescans everything. Written for E-Tech (public domain), inspired by the abandoned Resource Map Label Marker mod."},
  },
  {
    type = "int-setting",
    name = "etech-markers-min-size",
    setting_type = "runtime-global",
    default_value = 1,
    minimum_value = 1,
    maximum_value = 10000,
    order = "tk",
    localised_name = {"", "Resource markers: minimum patch size"},
    localised_description = {"", "Patches with fewer resource tiles than this don't get a map marker. 1 = mark everything."},
  },
  {
    type = "bool-setting",
    name = "etech-gleba-uranium",
    setting_type = "startup",
    default_value = false,
    order = "i",
    localised_name = {"", "Uranium bacteria on Gleba (Space Age)"},
    localised_description = {"", "Adds uranium bacteria, mirroring iron/copper bacteria: jelly gives a 1% chance of uranium bacteria (Jellynut tech), bacteria + bioflux multiplies it in a biochamber (Bacteria cultivation tech), and it spoils into uranium ore. Port of the abandoned Simple Gleba Uranium mod by cindersash. Needs Space Age; off by default."},
  },
})
